name: Release

env:
  sln-path: "./src/process watcher.sln"
  appproj-path: "./src/code/ProcessWatching.ConsoleApp/ProcessWatching.ConsoleApp.csproj"
  build-dir: "build"
  publish-dir: "build/publish"

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true

jobs:
  build:
    name: Build Release
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: .Net info
        run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore "${{ env.sln-path }}"

      - name: Build release
        run: dotnet build "${{ env.sln-path }}" -c Release --no-restore -o "${{ env.build-dir }}"

      - name: Create single exe file
        run: dotnet publish "${{ env.appproj-path }}" -c Release -o "${{ env.publish-dir }}" /p:PublishSingleFile=true /p:PublishTrimmed=true --self-contained true

      - name: Zip binaries
        uses: vimtor/action-zip@v1
        with:
          files: "${{ env.build-dir }}"
          dest: binaries.zip

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.ref_name }}
          prerelease: false
          draft: false
          generate_release_notes: true
          files: binaries.zip
